{{- if .Values.agent.useDeployment  }}
{{- $bucket := .Values.persistS3.bucket | required ".Values.persistS3.bucket is required for Deployments."}}
{{- end }}
{{- $clusterID := .Values.agent.clusterID | required ".Values.agent.clusterID is required."}}
apiVersion: apps/v1
{{- if .Values.agent.useDeployment  }}
kind: Deployment
{{- else }}
kind: StatefulSet
{{- end }}
metadata:
  name: {{ include "vantage-kubernetes-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vantage-kubernetes-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  {{- if .Values.agent.useDeployment }}
  strategy:
    type: Recreate
  {{- else }}
  serviceName: vantage-agent
  {{- end }}
  selector:
    matchLabels:
      {{- include "vantage-kubernetes-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vantage-kubernetes-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vantage-kubernetes-agent.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8}}
      {{- end}}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8}}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VANTAGE_DEBUG
              value: "{{ .Values.agent.debug }}"
            - name: VANTAGE_LOG_LEVEL
              value: "{{ .Values.agent.logLevel }}"
            - name: VANTAGE_CLUSTER_ID
              value: "{{ $clusterID }}"
            {{- if .Values.agent.disableKubeTLSverify}}
            - name: VANTAGE_KUBE_SKIP_TLS_VERIFY
              value: "{{ .Values.agent.disableKubeTLSverify }}"
            {{- end}}
            {{- if .Values.agent.nodeAddressTypes}}
            - name: VANTAGE_NODE_ADDRESS_TYPES
              value: "{{ .Values.agent.nodeAddressTypes }}"
            {{- end}}
            {{- if .Values.agent.allowedAnnotations}}
            - name: VANTAGE_ALLOWED_ANNOTATIONS
              value: "{{ .Values.agent.allowedAnnotations }}"
            {{- end}}
            {{- if .Values.agent.collectNamespaceLabels}}
            - name: VANTAGE_COLLECT_NAMESPACE_LABELS
              value: "{{ .Values.agent.collectNamespaceLabels }}"
            {{- end}}
            - name: VANTAGE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if .Values.agent.secret.name }}
                  name: {{ .Values.agent.secret.name }}
                  key: {{ .Values.agent.secret.key }}
                  {{- else }}
                  name: {{ include "vantage-kubernetes-agent.fullname" . }}
                  key: token
                  {{- end }}
            {{- with .Values.agent.apiHost }}
            - name: VANTAGE_API_HOST
              value: "{{ . }}"
            {{ end }}
            {{- with .Values.persistS3.bucket }}
            - name: VANTAGE_PERSIST_S3_BUCKET
              value: "{{ . }}"
            {{ end }}
            {{- with .Values.persistS3.prefix }}
            - name: VANTAGE_PERSIST_S3_PREFIX
              value: "{{ . }}"
            {{ end }}
            {{- with .Values.persist }}
            - name: VANTAGE_PERSIST_DIR
              value: "{{ .mountPath }}"
            {{ end }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if not .Values.agent.useDeployment }}
          {{- with .Values.persist }}
          volumeMounts:
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
  {{- if not .Values.agent.useDeployment }}
  {{- with .Values.persist }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .storageClassName }}
      storageClassName: {{ .storageClassName }}
      {{ end }}
      resources:
        requests:
          storage: {{ .size }}
  {{ end }}
  {{ end }}
