apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vantage-kubernetes-agent.fullname" . }}
  labels:
    {{- include "vantage-kubernetes-agent.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["nodes/metrics"]
  verbs: ["get"]
- apiGroups: ["", "apps", "batch"]
  resources:
  - "nodes"
  - "pods"
  - "namespaces"
  - "replicasets"
  - "replicationcontrollers"
  - "deployments"
  - "statefulsets"
  - "jobs"
  - "cronjobs"
  - "persistentvolumes"
  - "persistentvolumeclaims"
  verbs: ["get", "watch", "list"]
